/**
 * FmrVenta.java
 */
package proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author Nallely
 */
public class FmrVenta extends javax.swing.JFrame {

    /**
     * Creates new form venta
     */
    public FmrVenta() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuItemConfiguración = new javax.swing.JMenuItem();
        menuItemListarCajero = new javax.swing.JMenuItem();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemCerrarAplicacion = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuItemManejarClientes = new javax.swing.JMenuItem();
        menuItemListarClientes = new javax.swing.JMenuItem();
        menuVenta = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuItemHistorial = new javax.swing.JMenuItem();
        menuItemHistorialDetalleVenta = new javax.swing.JMenuItem();
        menuCategoria = new javax.swing.JMenu();
        menuItemAgregarCategoria = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuProducto = new javax.swing.JMenu();
        menuItemManejarProductos = new javax.swing.JMenuItem();
        menuItemListasProductos = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(242, 179, 39));
        setForeground(new java.awt.Color(242, 179, 39));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(738, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblImagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        menuBar.setForeground(new java.awt.Color(255, 233, 184));
        menuBar.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuBar.setPreferredSize(new java.awt.Dimension(362, 30));

        menuUsuario.setBackground(new java.awt.Color(255, 255, 255));
        menuUsuario.setForeground(new java.awt.Color(242, 113, 39));
        menuUsuario.setMnemonic('e');
        menuUsuario.setText("Usuario");
        menuUsuario.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        menuItemConfiguración.setBackground(new java.awt.Color(255, 255, 255));
        menuItemConfiguración.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemConfiguración.setMnemonic('t');
        menuItemConfiguración.setText("Configuración");
        menuItemConfiguración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConfiguraciónActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemConfiguración);

        menuItemListarCajero.setBackground(new java.awt.Color(255, 255, 255));
        menuItemListarCajero.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemListarCajero.setText("Listar cajeros");
        menuItemListarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarCajeroActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemListarCajero);

        menuItemCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        menuItemCerrarSesion.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemCerrarSesion.setMnemonic('p');
        menuItemCerrarSesion.setText("Cerrar sesión");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemCerrarSesion);

        menuItemCerrarAplicacion.setBackground(new java.awt.Color(255, 255, 255));
        menuItemCerrarAplicacion.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemCerrarAplicacion.setMnemonic('y');
        menuItemCerrarAplicacion.setText("Cerrar aplicación");
        menuItemCerrarAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarAplicacionActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemCerrarAplicacion);

        menuBar.add(menuUsuario);

        menuCliente.setBackground(new java.awt.Color(255, 255, 255));
        menuCliente.setForeground(new java.awt.Color(242, 113, 39));
        menuCliente.setMnemonic('e');
        menuCliente.setText("Clientes");
        menuCliente.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        menuItemManejarClientes.setBackground(new java.awt.Color(255, 255, 255));
        menuItemManejarClientes.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemManejarClientes.setText("Manejar Clientes");
        menuItemManejarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManejarClientesActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemManejarClientes);

        menuItemListarClientes.setBackground(new java.awt.Color(255, 255, 255));
        menuItemListarClientes.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemListarClientes.setText("Listar Clientes");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemListarClientes);

        menuBar.add(menuCliente);

        menuVenta.setBackground(new java.awt.Color(255, 255, 255));
        menuVenta.setForeground(new java.awt.Color(242, 113, 39));
        menuVenta.setText("Ventas");
        menuVenta.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jMenuItem4.setText("Generar venta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuVenta.add(jMenuItem4);

        menuItemHistorial.setBackground(new java.awt.Color(255, 255, 255));
        menuItemHistorial.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemHistorial.setText("Historial de venta");
        menuItemHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHistorialActionPerformed(evt);
            }
        });
        menuVenta.add(menuItemHistorial);

        menuItemHistorialDetalleVenta.setText("Historial detalle ventas");
        menuItemHistorialDetalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHistorialDetalleVentaActionPerformed(evt);
            }
        });
        menuVenta.add(menuItemHistorialDetalleVenta);

        menuBar.add(menuVenta);

        menuCategoria.setBackground(new java.awt.Color(255, 255, 255));
        menuCategoria.setForeground(new java.awt.Color(242, 113, 39));
        menuCategoria.setText("Categoria");
        menuCategoria.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        menuItemAgregarCategoria.setBackground(new java.awt.Color(255, 255, 255));
        menuItemAgregarCategoria.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemAgregarCategoria.setText("Manejar Categorias");
        menuItemAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgregarCategoriaActionPerformed(evt);
            }
        });
        menuCategoria.add(menuItemAgregarCategoria);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jMenuItem2.setText("Listar categorias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuCategoria.add(jMenuItem2);

        menuBar.add(menuCategoria);

        menuProducto.setBackground(new java.awt.Color(255, 255, 255));
        menuProducto.setForeground(new java.awt.Color(242, 113, 39));
        menuProducto.setMnemonic('e');
        menuProducto.setText("Productos");
        menuProducto.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        menuItemManejarProductos.setBackground(new java.awt.Color(255, 255, 255));
        menuItemManejarProductos.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemManejarProductos.setText("Manejar Productos");
        menuItemManejarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemManejarProductosActionPerformed(evt);
            }
        });
        menuProducto.add(menuItemManejarProductos);

        menuItemListasProductos.setBackground(new java.awt.Color(255, 255, 255));
        menuItemListasProductos.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        menuItemListasProductos.setText("Listar Productos");
        menuItemListasProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListasProductosActionPerformed(evt);
            }
        });
        menuProducto.add(menuItemListasProductos);

        menuBar.add(menuProducto);

        menuAyuda.setBackground(new java.awt.Color(255, 255, 255));
        menuAyuda.setForeground(new java.awt.Color(242, 113, 39));
        menuAyuda.setMnemonic('e');
        menuAyuda.setText("Ayuda");
        menuAyuda.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jMenuItem5.setText("Sobre nosotros");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuAyuda.add(jMenuItem5);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FmrModuloVentas mv = new FmrModuloVentas();
        mv.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuItemManejarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManejarClientesActionPerformed
        DlgNuevoCliente nC = new DlgNuevoCliente(this, true);
        nC.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemManejarClientesActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        // TODO add your handling code here:
        DlgClientes dlgClientes = new DlgClientes();
        dlgClientes.setVisible(true);
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void menuItemConfiguraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConfiguraciónActionPerformed
        // TODO add your handling code here:
        DlgConfiguracion dlgConfiguracion = new DlgConfiguracion(this, true);
        dlgConfiguracion.setVisible(true);
    }//GEN-LAST:event_menuItemConfiguraciónActionPerformed

    private void menuItemCerrarAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarAplicacionActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_menuItemCerrarAplicacionActionPerformed

    private void menuItemAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgregarCategoriaActionPerformed
        // TODO add your handling code here:
        DlgNuevaCategoria dlgNuevaCategoria = new DlgNuevaCategoria(this, true);
        dlgNuevaCategoria.setVisible(true);
    }//GEN-LAST:event_menuItemAgregarCategoriaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DlgCategoria dlgCategoria = new DlgCategoria();
        dlgCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        // TODO add your handling code here:
        DlgLogIn login = new DlgLogIn();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemListarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarCajeroActionPerformed
        // TODO add your handling code here:
        DlgCajero dlgCajero = new DlgCajero();
        dlgCajero.setVisible(true);
    }//GEN-LAST:event_menuItemListarCajeroActionPerformed

    private void menuItemManejarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemManejarProductosActionPerformed
        // TODO add your handling code here:
        DlgNuevoProducto dlgProducto = new DlgNuevoProducto(this, true);
        dlgProducto.setVisible(true);
    }//GEN-LAST:event_menuItemManejarProductosActionPerformed

    private void menuItemListasProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListasProductosActionPerformed
        // TODO add your handling code here:
        DlgProductos dlgProductos = new DlgProductos();
        dlgProductos.setVisible(true);
    }//GEN-LAST:event_menuItemListasProductosActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hecho por:\n"
                + " Fernando Acosta\n"
                + "Andrea Felix\n"
                + "Nallely Bracamontes\n"
                + "Derechos reservados 2020\n"
                + "3er semestre de la carrera de ingenieria en software\n"
                + "Itson Nairani", "Acerca de nosotros", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuItemHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHistorialActionPerformed
        // TODO add your handling code here:
        DlgHistorialVenta dlgHistorialVenta = new DlgHistorialVenta();
        dlgHistorialVenta.setVisible(true);
    }//GEN-LAST:event_menuItemHistorialActionPerformed

    private void menuItemHistorialDetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHistorialDetalleVentaActionPerformed
        // TODO add your handling code here:
        DlgHistorialDetalleVenta dlgHistoriaDetalleVenta = new DlgHistorialDetalleVenta();
        dlgHistoriaDetalleVenta.setVisible(true);
    }//GEN-LAST:event_menuItemHistorialDetalleVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuItemAgregarCategoria;
    private javax.swing.JMenuItem menuItemCerrarAplicacion;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemConfiguración;
    private javax.swing.JMenuItem menuItemHistorial;
    private javax.swing.JMenuItem menuItemHistorialDetalleVenta;
    private javax.swing.JMenuItem menuItemListarCajero;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListasProductos;
    private javax.swing.JMenuItem menuItemManejarClientes;
    private javax.swing.JMenuItem menuItemManejarProductos;
    private javax.swing.JMenu menuProducto;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVenta;
    // End of variables declaration//GEN-END:variables

}
